import 'package:flutter/material.dart';

class HomeNotifier extends ChangeNotifier {
  final BuildContext context;

  HomeNotifier(this.context);
  
  final List c = [
    "Rp. 330.000",
    "Rp. 699.300",
    "Rp. 299.000",
    "Rp. 143.200",
    "Rp. 579.000",
    "Rp. 199.000",
    "Rp. 899.300",
    "Rp. 159.300",
    "Rp. 199.300",
    "Rp. 389.300",
    "Rp. 259.300",
    "Rp. 4.199.000",
    "Rp. 129.000",
    "Rp. 599.000",
    "Rp. 1.199.300",
    "Rp. 559.000",
    "Rp. 159.000",
    "Rp. 900.000",
    "Rp. 299.000",
    "Rp. 2.999.000",
    "Rp. 559.000",
    "Rp. 73.500",
    "Rp. 459.000",
    "Rp. 79.000",
    "Rp. 260.000",
    "Rp. 202.000",
    "Rp. 370.860",
    "Rp. 900.000",
    "Rp. 331.415",
    "Rp. 169.000",
  ];
  final List b = [
    "Adidas Tabela 23 Men's Jersey - Black",
    "New Balance Fresh Foam Arishi V4 Women's Running- Arctic Grey With Light Arctic Grey",
    "Puma Active Big Logo Men's T-Shirt - Dark Blue",
    "ASTEC GIZA WOMEN' LONGSLEEVE TSHIRT - NAVY",
    "Nike Flex Runner 2 JP Baby/Toddler Shoes - Black",
    "SKECHERS MINI SOCCER BALL Unisex's Football - BLACK WHITE",
    "Skechers GOrun Elevate - Accelerate Men's Running Shoes - Off White",
    "SKECHERS 3PK NO SHOW PRF MEN'S SOCKS - MULTICOLOR",
    "DIADORA GELANG MEN'S T-SHIRT - BLACK",
    "Nike Liverpool FC Strike Soccer Ball - Red",
    "Spalding 2021 Varsity Fiba TF150 Basketball - Orange",
    "Babolat PA Team RAFA Unstrung No Cover - Yellow",
    "ASTEC HENI WOMEN'S BASIC TSHIRT - BLACK",
    "Skechers Twi Lites Star Amazing Girl's Sneakers Shoes - WHITE/SILVER",
    "Reebok Glide Ripple Men Lifestyle Shoes - Black",
    "Diadora Gustavo Women Running Shoes - Purple",
    "Airwalk Shantal Tshirt JR Girls- Black",
    "Adidas Super Sala 2 Indoor Men's Futsal Shoes - Night Grey",
    "Puma Active Big Logo Men's T-Shirt - Dark Blue",
    "Babolat RH12 Pure Aero RAFA Tennis Racket Bag - Orange/Purple",
    "Mikasa Volly-V330W",
    "Tennis ball Dunlop Fort 3",
    "ASTEC HURLEY MEN'S FUTSAL - NAVY",
    "Reebok ANKLE Boy's Socks - Misty71/Dark Grey/Black",
    "Molten H2R - Handball Original",
    "MOLTEN Net Volley VN-003",
    "Specs Original Hyperchaos FG Meta Crush Pack 101990 BNIB",
    "Nassau Bola Volly New Premium",
    "Space Run Eagle Shoes",
    "SPECS ILLUZION II MADA FB TRAINING BALL - WHITE/CYAN/PINK",
  ];
  List a = [
    "assets/list/1.jpeg",
    "assets/list/2.jpg",
    "assets/list/3.jpg",
    "assets/list/4.jpg",
    "assets/list/5.jpg",
    "assets/list/6.jpg",
    "assets/list/7.jpg",
    "assets/list/8.jpg",
    "assets/list/9.jpg",
    "assets/list/10.jpg",
    "assets/list/11.jpg",
    "assets/list/12.jpg",
    "assets/list/13.jpg",
    "assets/list/14.jpg",
    "assets/list/15.jpg",
    "assets/list/16.jpg",
    "assets/list/17.jpg",
    "assets/list/18.jpg",
    "assets/list/19.jpg",
    "assets/list/20.jpg",
    "assets/list/21.jpg",
    "assets/list/22.jpeg",
    "assets/list/23.jpg",
    "assets/list/24.jpg",
    "assets/list/25.jpeg",
    "assets/list/26.jpg",
    "assets/list/27.jpg",
    "assets/list/28.jpeg",
    "assets/list/29.jpeg",
    "assets/list/30.jpeg",
  ];

  List d = [
    'assets/kat/1.jpeg',
    'assets/kat/2.jpg',
    'assets/kat/3.jpeg',
    'assets/kat/4.jpg',
    'assets/kat/5.jpg'
  ];

}
